[project]
name = "rag-processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.10",
    "langchain-community>=0.3.24",
    "langchain-ollama>=0.3.3",
    "loguru>=0.7.3",
]
